### ISSUE TITLE
Button to switch from L2A to L1C should be visible when L1C products are available

### ISSUE THREAD

**Issue by mkadunc** [sinergise/EOBrowser#2]
I have L2A turned on. I move the map view to Egypt, where there is no L2A products available. Now I don't see anything and there is no button which I could use to switch back to L1C.

**Comment by mkadunc** [comment]
Example - in Greece, L2A is available, and the app allows me to switch to L1C
![greece](https://user-images.githubusercontent.com/10532824/30061069-36c1ac76-9246-11e7-9d6c-199b14cbee99.jpg)
in Libya, L2A is not available from some latitude onwards, but the app does not show the L1C button any more,
![africa](https://user-images.githubusercontent.com/10532824/30061073-3b4bee64-9246-11e7-8a0a-4f756ac1292b.jpg)
although there are L1C images available for that same date on that same area - as can be seen by going back to Greece, switching to L1C and scrolling back to Libya
![africal1c](https://user-images.githubusercontent.com/10532824/30061075-3dc7354a-9246-11e7-8a8b-38a59c3a212e.jpg)

**Comment by themre** [comment]
fixed, thanks. L1C button will be always visible, query will tell you if there are really data on that date or not.
